##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. See LICENSE file
## in root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_screen
description: "A tool to generate ready-made screen templates for your Flutter app (uses df_sceen) #CodeGenerator"
version: 0.1.0+2
repository: https://github.com/robmllze/df_generate_screen
publish_to: none

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  analyzer: ^6.8.0
  args: ^2.5.0
  df_collection: ^0.2.0
  df_config: ^0.1.2
  df_gen_core: ^0.2.3
  df_log: ^0.1.2
  df_string: ^0.1.2
  df_type: ^0.1.4
  df_generate_dart_models_core: ">=0.2.2 <0.3.0"
  path: ^1.9.0

  df_screen_core:
    git:
      url: https://github.com/robmllze/df_screen_core
      ref: main

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

## -----------------------------------------------------------------------------

executables:
  df_generate_screen: generate_screen
  generate_screen: generate_screen
  genscr: generate_screen

  df_generate_screen_access: generate_screen_access
  generate_screen_access: generate_screen_access
  genscr-access: genscreenaccess

  df_generate_screen_bindings: generate_screen_bindings
  generate_screen_bindings: generate_screen_bindings
  genscr-bindings: generate_screen_bindings
