##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_screen
description: A tool to generate ready-made screen templates for your Flutter app (uses df_sceen)
version: 0.2.6
repository: https://github.com/devcetra/df_generate_screen
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - source-gen
  - build-runner
  - code-generation
  - screen
  - pages

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_collection: ^0.6.1
  df_config: ^0.5.0
  df_gen_core: ^0.3.2
  df_generate_dart_indexes: ^0.3.1
  df_generate_dart_models_core: ^0.6.4
  df_log: ^0.2.4
  df_screen_core: ^0.2.4
  df_string: ^0.2.2
  df_type: ^0.6.2

  analyzer: ^6.8.0
  args: ^2.5.0
  path: ^1.9.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

## -----------------------------------------------------------------------------

executables:
  genscr: genscr-v4
  genscr-access: genscr-access-v4
  genscr-bindings: genscr-bindings-v4

  genscr-v1: genscr-v1
  genscr-access-v1: genscr-access-v1
  genscr-bindings-v1: genscr-bindings-v1

  genscr-v2: genscr-v2
  genscr-access-v2: genscr-access-v2
  genscr-bindings-v2: genscr-bindings-v2
