##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_screen
description: A tool to generate ready-made screen templates for your Flutter app (uses df_sceen)
version: 0.5.2
repository: https://github.com/devcetra/df_generate_screen
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - source-gen
  - build-runner
  - code-generation
  - screen
  - pages

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_collection: ^0.8.3
  df_config: ^0.5.3
  df_gen_core: ^0.4.5
  df_generate_dart_indexes: ^0.4.1
  df_generate_dart_models_core: ^0.8.0
  df_log: ^0.2.4
  df_screen_core: ^0.3.0
  df_string: ^0.2.3
  df_type: ^0.7.2

  analyzer: ^6.8.0
  args: ^2.6.0
  path: ^1.9.1

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

## -----------------------------------------------------------------------------

executables:
  gen-screen: dfscr-v6
  gen-screen-access: dfscr-access-v6
  gen-screen-bindings: dfscr-bindings-v6
